// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskSurvey.Infrastructure.Data;

#nullable disable

namespace TaskSurvey.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260127035619_Init_With_Seeder")]
    partial class Init_With_Seeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.DocumentItemDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<int>("TemplateItemDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentItemId");

                    b.HasIndex("TemplateItemDetailId");

                    b.ToTable("DocumentItemDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3935),
                            DocumentItemId = 2,
                            IsChecked = true,
                            TemplateItemDetailId = 1,
                            UpdatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3939)
                        });
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.DocumentSurvey", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TemplateHeaderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("TemplateHeaderId");

                    b.ToTable("DocumentSurveys");

                    b.HasData(
                        new
                        {
                            DocumentId = "SURVEY/2601/0001",
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3773),
                            RequesterId = "00000002",
                            Status = 0,
                            TemplateHeaderId = "TEMPLATE/2601/001",
                            UpdatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3777)
                        });
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.DocumentSurveyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentSurveyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TemplateItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentSurveyId");

                    b.HasIndex("TemplateItemId");

                    b.ToTable("DocumentSurveyItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Lingkungan kerja sangat kondusif dan mendukung produktivitas.",
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3850),
                            DocumentSurveyId = "SURVEY/2601/0001",
                            TemplateItemId = 1,
                            UpdatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3853)
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Selected",
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3857),
                            DocumentSurveyId = "SURVEY/2601/0001",
                            TemplateItemId = 2,
                            UpdatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3859)
                        });
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PositionLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 97, DateTimeKind.Local).AddTicks(2894),
                            PositionLevel = "Officer"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 97, DateTimeKind.Local).AddTicks(2898),
                            PositionLevel = "Section Head"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 97, DateTimeKind.Local).AddTicks(2900),
                            PositionLevel = "Departement Head"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 97, DateTimeKind.Local).AddTicks(2902),
                            PositionLevel = "Director"
                        });
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 97, DateTimeKind.Local).AddTicks(2621),
                            RoleName = "Supervisor"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 97, DateTimeKind.Local).AddTicks(2650),
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateHeader", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("TemplateHeaders");

                    b.HasData(
                        new
                        {
                            Id = "TEMPLATE/2601/001",
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3363),
                            PositionId = 3,
                            TemplateName = "Survey Kepuasan Kerja",
                            Theme = "Blue Corporate",
                            UpdatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3373)
                        });
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateHeaderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TemplateHeaderId");

                    b.ToTable("TemplateItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3479),
                            Question = "Apa pendapat Anda tentang lingkungan kerja?",
                            TemplateHeaderId = "TEMPLATE/2601/001",
                            Type = 2,
                            UpdatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3488)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3492),
                            Question = "Fasilitas yang Anda gunakan:",
                            TemplateHeaderId = "TEMPLATE/2601/001",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3494)
                        });
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateItemDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemplateItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TemplateItemId");

                    b.ToTable("TemplateItemDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3672),
                            Item = "Laptop Inventaris",
                            TemplateItemId = 2,
                            UpdatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3678)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3681),
                            Item = "Ruang Meeting",
                            TemplateItemId = 2,
                            UpdatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3683)
                        });
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "00000001",
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 183, DateTimeKind.Local).AddTicks(7293),
                            PasswordHash = "AQAAAAIAAYagAAAAEKafilhRdKTWxe9pneqG1DqsXCVHpr3XXPxM0T+vSaO73b8wzz3Zdf1Pe8ZkX/XDKA==",
                            PositionId = 3,
                            PositionName = "Departement Leader",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 183, DateTimeKind.Local).AddTicks(7336),
                            Username = "Wahyu Johan"
                        },
                        new
                        {
                            Id = "00000002",
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 183, DateTimeKind.Local).AddTicks(7355),
                            PasswordHash = "AQAAAAIAAYagAAAAEKafilhRdKTWxe9pneqG1DqsXCVHpr3XXPxM0T+vSaO73b8wzz3Zdf1Pe8ZkX/XDKA==",
                            PositionId = 1,
                            PositionName = "IT Staff",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 183, DateTimeKind.Local).AddTicks(7364),
                            Username = "Andhika"
                        });
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.UserRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupervisorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserRelations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 27, 10, 56, 19, 184, DateTimeKind.Local).AddTicks(3200),
                            SupervisorId = "00000001",
                            UserId = "00000002"
                        });
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.DocumentItemDetail", b =>
                {
                    b.HasOne("TaskSurvey.Infrastructure.Models.DocumentSurveyItem", "DocumentSurveyItem")
                        .WithMany("CheckBox")
                        .HasForeignKey("DocumentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskSurvey.Infrastructure.Models.TemplateItemDetail", "TemplateItemDetail")
                        .WithMany("ItemDetails")
                        .HasForeignKey("TemplateItemDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentSurveyItem");

                    b.Navigation("TemplateItemDetail");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.DocumentSurvey", b =>
                {
                    b.HasOne("TaskSurvey.Infrastructure.Models.User", "Requester")
                        .WithMany("Documents")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TaskSurvey.Infrastructure.Models.TemplateHeader", "Header")
                        .WithMany("Surveys")
                        .HasForeignKey("TemplateHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Header");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.DocumentSurveyItem", b =>
                {
                    b.HasOne("TaskSurvey.Infrastructure.Models.DocumentSurvey", "DocumentSurvey")
                        .WithMany("SurveyItems")
                        .HasForeignKey("DocumentSurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskSurvey.Infrastructure.Models.TemplateItem", "TemplateItem")
                        .WithMany("SurveyItems")
                        .HasForeignKey("TemplateItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentSurvey");

                    b.Navigation("TemplateItem");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateHeader", b =>
                {
                    b.HasOne("TaskSurvey.Infrastructure.Models.Position", "Position")
                        .WithMany("Headers")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateItem", b =>
                {
                    b.HasOne("TaskSurvey.Infrastructure.Models.TemplateHeader", "TemplateHeader")
                        .WithMany("Items")
                        .HasForeignKey("TemplateHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateHeader");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateItemDetail", b =>
                {
                    b.HasOne("TaskSurvey.Infrastructure.Models.TemplateItem", "TemplateItem")
                        .WithMany("ItemDetails")
                        .HasForeignKey("TemplateItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateItem");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.User", b =>
                {
                    b.HasOne("TaskSurvey.Infrastructure.Models.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskSurvey.Infrastructure.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.UserRelation", b =>
                {
                    b.HasOne("TaskSurvey.Infrastructure.Models.User", "Supervisor")
                        .WithMany("SubordinateRelations")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskSurvey.Infrastructure.Models.User", "User")
                        .WithMany("SupervisorRelations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supervisor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.DocumentSurvey", b =>
                {
                    b.Navigation("SurveyItems");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.DocumentSurveyItem", b =>
                {
                    b.Navigation("CheckBox");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.Position", b =>
                {
                    b.Navigation("Headers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateHeader", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateItem", b =>
                {
                    b.Navigation("ItemDetails");

                    b.Navigation("SurveyItems");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateItemDetail", b =>
                {
                    b.Navigation("ItemDetails");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.User", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("SubordinateRelations");

                    b.Navigation("SupervisorRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
