// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskSurvey.Infrastructure.Data;

#nullable disable

namespace TaskSurvey.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.DocumentItemDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<int>("TemplateItemDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentItemId");

                    b.HasIndex("TemplateItemDetailId");

                    b.ToTable("DocumentItemDetails");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.DocumentSurvey", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TemplateHeaderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("TemplateHeaderId");

                    b.ToTable("DocumentSurveys");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.DocumentSurveyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentSurveyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TemplateItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentSurveyId");

                    b.HasIndex("TemplateItemId");

                    b.ToTable("DocumentSurveyItems");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PositionLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 26, 16, 38, 31, 382, DateTimeKind.Local).AddTicks(3511),
                            PositionLevel = "Officer"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 26, 16, 38, 31, 382, DateTimeKind.Local).AddTicks(3514),
                            PositionLevel = "Section Head"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 26, 16, 38, 31, 382, DateTimeKind.Local).AddTicks(3515),
                            PositionLevel = "Departement Head"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 26, 16, 38, 31, 382, DateTimeKind.Local).AddTicks(3517),
                            PositionLevel = "Director"
                        });
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 26, 16, 38, 31, 382, DateTimeKind.Local).AddTicks(3287),
                            RoleName = "Supervisor"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 26, 16, 38, 31, 382, DateTimeKind.Local).AddTicks(3315),
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateHeader", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("TemplateHeaders");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateHeaderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TemplateHeaderId");

                    b.ToTable("TemplateItems");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateItemDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemplateItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TemplateItemId");

                    b.ToTable("TemplateItemDetails");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 26, 16, 38, 31, 454, DateTimeKind.Local).AddTicks(6363),
                            PasswordHash = "AQAAAAIAAYagAAAAEGy2HrmcXlm8L0Sj0uPZZNBL7CoUXjQJvxhMhO75msg3OFNA2LTtV53qgGm1Xsaj5Q==",
                            PositionId = 3,
                            PositionName = "Departement Leader",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2026, 1, 26, 16, 38, 31, 454, DateTimeKind.Local).AddTicks(6408),
                            Username = "Wahyu Johan"
                        });
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.UserRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserRelations");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.DocumentItemDetail", b =>
                {
                    b.HasOne("TaskSurvey.Infrastructure.Models.DocumentSurveyItem", "DocumentSurveyItem")
                        .WithMany("CheckBox")
                        .HasForeignKey("DocumentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskSurvey.Infrastructure.Models.TemplateItemDetail", "TemplateItemDetail")
                        .WithMany("ItemDetails")
                        .HasForeignKey("TemplateItemDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentSurveyItem");

                    b.Navigation("TemplateItemDetail");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.DocumentSurvey", b =>
                {
                    b.HasOne("TaskSurvey.Infrastructure.Models.User", "Requester")
                        .WithMany("Documents")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TaskSurvey.Infrastructure.Models.TemplateHeader", "Header")
                        .WithMany("Surveys")
                        .HasForeignKey("TemplateHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Header");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.DocumentSurveyItem", b =>
                {
                    b.HasOne("TaskSurvey.Infrastructure.Models.DocumentSurvey", "DocumentSurvey")
                        .WithMany("SurveyItems")
                        .HasForeignKey("DocumentSurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskSurvey.Infrastructure.Models.TemplateItem", "TemplateItem")
                        .WithMany("SurveyItems")
                        .HasForeignKey("TemplateItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentSurvey");

                    b.Navigation("TemplateItem");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateHeader", b =>
                {
                    b.HasOne("TaskSurvey.Infrastructure.Models.Position", "Position")
                        .WithMany("Headers")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateItem", b =>
                {
                    b.HasOne("TaskSurvey.Infrastructure.Models.TemplateHeader", "TemplateHeader")
                        .WithMany("Items")
                        .HasForeignKey("TemplateHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateHeader");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateItemDetail", b =>
                {
                    b.HasOne("TaskSurvey.Infrastructure.Models.TemplateItem", "TemplateItem")
                        .WithMany("ItemDetails")
                        .HasForeignKey("TemplateItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateItem");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.User", b =>
                {
                    b.HasOne("TaskSurvey.Infrastructure.Models.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskSurvey.Infrastructure.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.UserRelation", b =>
                {
                    b.HasOne("TaskSurvey.Infrastructure.Models.User", "Supervisor")
                        .WithMany("SubordinateRelations")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskSurvey.Infrastructure.Models.User", "User")
                        .WithMany("SupervisorRelations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supervisor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.DocumentSurvey", b =>
                {
                    b.Navigation("SurveyItems");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.DocumentSurveyItem", b =>
                {
                    b.Navigation("CheckBox");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.Position", b =>
                {
                    b.Navigation("Headers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateHeader", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateItem", b =>
                {
                    b.Navigation("ItemDetails");

                    b.Navigation("SurveyItems");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.TemplateItemDetail", b =>
                {
                    b.Navigation("ItemDetails");
                });

            modelBuilder.Entity("TaskSurvey.Infrastructure.Models.User", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("SubordinateRelations");

                    b.Navigation("SupervisorRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
